### ISSUE TITLE
Bright quiescent galaxies

### ISSUE THREAD

**Issue by OlivierKauffmann** [JADES-GTO/JAGUAR_extragalactic_mock_catalog#10]
I have just noticed that the brightest UV sources are passive, which sounds weird to me, especially from the fact that they are much less numerous. Here are attached some plot of magnitudes (absolute UV, HST fluxes in V and K band) versus stellar mass for star-forming and quiescent galaxies. There seems to be unexpected trends/differences between active and passive galaxies of similar stellar mass.
![muv versus mstar](https://user-images.githubusercontent.com/38685988/48494227-bbfea400-e82d-11e8-9cbf-071911b00ca6.png)
![v versus mstar](https://user-images.githubusercontent.com/38685988/48494236-be60fe00-e82d-11e8-9a10-c5415f27b7ec.png)
![k versus mstar](https://user-images.githubusercontent.com/38685988/48494244-c0c35800-e82d-11e8-9525-383ba617cf4d.png)

**Comment by jacopo-chevallard** [comment]
Thanks for pointing this out @OlivierKauffmann, we'll take a look and get back to you asap

**Comment by OlivierKauffmann** [comment]
Here the star formation rate (SFR = sSFR + mStar for quiescent galaxies, which corresponds to SFR_100 for star-forming galaxies) versus stellar mass. Again, it sounds weird to have massive quiescent galaxies with SFR similar to massive star-forming galaxies. Maybe this can help.
![sfr versus mstar](https://user-images.githubusercontent.com/38685988/48565387-bae67900-e8f8-11e8-8750-a28b632c4ff6.png)

**Comment by jacopo-chevallard** [comment]
@eclake the explanation for the presence of quiescent galaxies with large sSFR and bright UV is that we just took fits to 3D-HST galaxies which were (empirically) classified as quiescent from the UVJ diagram, but that Beagle could fit with dusty, star-forming templates, and we just randomly draw from the posterior without forcing a low sSFR? (As explained in Sec 4.2 of the paper)

**Comment by OlivierKauffmann** [comment]
One remaining problem is that no dust attenuation is considered for quiescent galaxies in your model, which makes real issues especially at blue wavelengths (in the figure MUV versus mStar in the bottom-right corner). Would there be a simple way to include dust attenuation a posteriori ?

**Comment by eclake** [comment]
Hi @OlivierKauffmann - there was actually an error in the mocks that has only been corrected in v1.2 (but that hasn't been 'officially' released yet) - there was dust in the 3dHST fitting, that the SEDs were sampled from, but it wasn't included when re-making the mock.  I just wanted to double check what version you made the above plots with?  The v1.2 are available on the ftp and we should put together the proper release shortly!

**Comment by OlivierKauffmann** [comment]
Hi @eclake. I made the above plots with the v1.1. As repeated twice in another issue, the access to v1.2 galaxy catalogs on - https://neogal.iap.fr/ - is stll forbidden, so I could not have used this version (nor the spectra extended to 30 microns). I assume I will need to wait for the next release that will hopefully come soon.

**Comment by eclake** [comment]
Hi @OlivierKauffmann - thank you so much for your patience! I've replied to the other thread reagarding the quiescent galaxy downgraded spectra, however - @jacopo-chevallard please can you also check whether you can download v1.2 catalogue files?  I was not aware you didn't have access to them either, Olivier, I'm sorry for that - they are meant to be available.  If you still cannot access them we should start a new issue!

**Comment by jacopo-chevallard** [comment]
@OlivierKauffmann : can you tell me exactly what happens with the ftp? Are you unable to reach the site https://neogal.iap.fr ? If you access the site, which folders do you see? You should see something like, do you?

![screen shot 2018-12-04 at 11 18 16](https://user-images.githubusercontent.com/8123595/49435194-51021680-f7b6-11e8-8d25-057047b157e3.png)

**Comment by OlivierKauffmann** [comment]
Hi @eclake @jacopo-chevallard - I do have access to the website, but some file are forbidden. Here is the complete list of files I cannot access:
- r1/JADES_Q_mock_r1_v1.2.fits.gz 
- r1/JADES_Q_mock_r1_v1.2_spec_5A_30um.fits.gz 
- r#/JADES_Q_mock_r2_v1.2.fits.gz
- r#/JADES_SF_mock_r2_v1.2.fits.gz  
- r#/JADES_SF_mock_r2_v1.2_fluxes_noLya.fits.gz  
with #=2,3,...,10

**Comment by OlivierKauffmann** [comment]
Forbidden
You don't have permission to access /JAGUAR_mock_catalogue/r10/JADES_Q_mock_r10_v1.2.fits.gz on this server.

**Comment by eclake** [comment]
OK, done - can you access it now?

**Comment by jacopo-chevallard** [comment]
I can, let's wait for @OlivierKauffmann confirmation !

**Comment by OlivierKauffmann** [comment]
It looks like the problem is solved. Many thanks

**Comment by eclake** [comment]
Thanks @jacopo-chevallard ! and thank you @OlivierKauffmann for bringing it to our attention!  Sorry it fell through the net and took so long to implement the simple fix!

**Comment by OlivierKauffmann** [comment]
"there was actually an error in the mocks that has only been corrected in v1.2" - I quickly checked the Q catalog. There is effectively the additional column tauV_eff with non-zero values for galaxies above the stellar mass threshold of 8.7+0.4z. This sounds good. I will come back to you as soon as I can compute the M_UV for quiescent galaxies (see issue #5)

**Comment by OlivierKauffmann** [comment]
Here are attached some plot of magnitudes versus stellar mass (absolute MUV and HST/F606W, as before). The high-mass quiescent galaxies now have fainter UV magnitudes, or at least not brighter than star-forming galaxies any more. The change in the V band is also noticable.
![mstar versus muv](https://user-images.githubusercontent.com/38685988/49651050-726d3780-fa2e-11e8-85e2-8bcd851621e0.png)
![mstar versus f606w](https://user-images.githubusercontent.com/38685988/49651055-74cf9180-fa2e-11e8-9594-c0e10c57bce0.png)

**Comment by JADES-GTO** [comment]
issue was solved
