### ISSUE TITLE
Link to documentation broken

### ISSUE THREAD

**Issue by coljac** [JADES-GTO/JAGUAR_extragalactic_mock_catalog#13]
On the Jaguar website, there's a link to "Documentation", pointing to https://fenrir.as.arizona.edu/jaguar/jades-mock-catalog.pdf, which gives a 404 error.

**Comment by christinawilliams** [comment]
Whoops, thanks for letting us know. Until we get it back up, I've attached the documentation here. Will let you know when its back up. 
[JADES_mock_catalog_documentation.pdf](https://github.com/JADES-GTO/JAGUAR_extragalactic_mock_catalog/files/5337674/JADES_mock_catalog_documentation.pdf)

**Comment by coljac** [comment]
Thanks for the quick response, that's very helpful!

**Comment by kevinhainline** [comment]
We've updated the webpage everywhere with the proper link to the documentation! Thanks for pointing this out.
