### ISSUE TITLE
Sprectra extension to higher wavelengths

### ISSUE THREAD

**Issue by OlivierKauffmann** [JADES-GTO/JAGUAR_extragalactic_mock_catalog#5]
The current wavelength upper limit for the galaxy spectra is 10 microns. Would it be possible to extent to 30 microns for example ? I am currently trying to add some dust emission contribution to the actual spectra, starting from some FIR templates. Between the stellar and the dust contributions, a smooth transition requires both spectra to extent to each other's wavelength domain. For the moment, I somehow extrapolated your spectra to higher wavelength (fast decrease to zero). An extension to 30 microns would help.

**Comment by eclake** [comment]
Hi @OlivierKauffmann,
Sorry for the slow reply!
Yes, I think this should be fairly simple to implement - we will be releasing extra realizations soon so I will try to include the longer wavelength coverage in them (I also might be able to send you a version of r1 in the next couple of days going to 30 microns)

Thanks!
Emma

**Comment by jacopo-chevallard** [comment]
@eclake we have a new version which extends to longer wl, right?

**Comment by eclake** [comment]
@OlivierKauffmann, @jacopo-chevallard Yes, there is a version that hasn't been officially released (v1.2) but it can be downloaded from the iap ftp server - https:/neogal.iap.fr - let me know if you have an problems downloading it!

**Comment by OlivierKauffmann** [comment]
Thanks a lot

**Comment by OlivierKauffmann** [comment]
Apparently it is forbidden to download the JADES_Q_mock_r#_v1.2.fits.gz  files, but apart from that it is fine

**Comment by OlivierKauffmann** [comment]
Concerning the maximum wavelength, it seems that the initial limit of 10 microns has been decreased to 3 microns (30,000 Angstrom) instead of being increased to 30 microns (300,000 Angstrom). This is what I observed in this file: 
JADES_SF_mock_r1_v1.2_spec_5A_30um_z_0p2_1.fits

**Comment by eclake** [comment]
Oh no, that's thoroughly stupid of me not to have noticed! Let me dig around and see what happened!

**Comment by eclake** [comment]
@OlivierKauffmann OK, I think I've found the problem but the new files won't be ready before monday, will message here when they're posted to the ftp - sorry about that!

**Comment by OlivierKauffmann** [comment]
Any news ?

**Comment by eclake** [comment]
Hi @OlivierKauffmann - sorry for the delay! I'm having to change the setup as the file sizes are so large with the extra wavelength range but I'm working on it.

**Comment by eclake** [comment]
Hi @OlivierKauffmann - the files are numerous and large with an extension to 30um (we're looking at ~40Gb for one realisation).  So, are there any redshifts that you are more interested in than others?  Could I put together a subset for you from the different realizations?  Are you happy with downloading 40Gb split between ~20 files?  I can still upload them for r1 but I will keep the other realizations to a long wavelength limit of 10um.

**Comment by OlivierKauffmann** [comment]
Hi @eclake. I am interested in the whole redshift range. Downloading 40 Gb is not an issue for me. You can do as you said, one realization is probably enough for my purpose.

There may be another solution. Each spectra currently consists of 3075 points with resolution of 100 Angstrom at the red end. Keeping the same resolution up to 30 microns gives 2000 additional points. I assume the spectra in the region 10-30 microns are fairly smooth. If there are no emission line, the spectral resolution does not need to be very thin. By increasing the spectral resolution in this region (> 200 Angstrom for example), the files would not be so much bigger than the previous ones. What do you think ?

**Comment by eclake** [comment]
Good point!  I'll check it out!

**Comment by eclake** [comment]
Hi @OlivierKauffmann - the (large) data files extended to 30um are available on the neogal ftp server (where you grabbed them from previously) under r1_30um_cutoff.  There are lines in the longer wavelength region, so your very sensible suggestion isn't so simple.  I would like to implement it for all the realizations in the end but at the moment I'm finding it hard to dedicate time to it, and didn't want to keep you waiting any longer for the spectra!

**Comment by OlivierKauffmann** [comment]
Hi @eclake. Thank you very much for the spectra, I will have a look at the files. May I ask you to upload the galaxy characteristics fits files (one for SF, one for Q), please ? Or maybe these galaxies are the same as in a previous realization ? You called the folder "r1_30um_cutoff" but the file names contain "r10", so I am a bit confused.

**Comment by eclake** [comment]
Sorry! I copied from the wrong folder! Yes, I'll re-load the r1 ones, good spot - they shouldn't take too long to upload

**Comment by eclake** [comment]
but it might be a few hours...

**Comment by OlivierKauffmann** [comment]
Hi @eclake. Sorry to bother you again, but I found some problems.

For the SF spectra, you took a resolution of 25 A above 1.5 microns (total of 15721 points per spectrum), while you previously (v1.1) used 50 A above 1.5 microns and 100 A above 3 microns (total of 3075 points per spectrum). I assume you took a such small resolution to correctly recover the emission lines you mentionned. The SF r1 catalog is in agreement with my computation of the fluxes from the new spectra. I noticed that the stellar emission increases again beyond 20 microns for most galaxies, is it expected (I am not a specialist) ? 

For the Q spectra, the wavelength and the spectra dimensions mismatch (SED:(7464, 13871), WL:(3184,)), and the access to the Q galaxies characteristics (r1/JADES_Q_mock_r1_v1.2.fits.gz) is still forbidden. Can you do something with this ?

**Comment by OlivierKauffmann** [comment]
Here is an example of SF galaxy spectra with emission lines
![figure_1](https://user-images.githubusercontent.com/38685988/49234494-6cf16b00-f3f8-11e8-9ac8-bd7b9b9f2029.png)

**Comment by jacopo-chevallard** [comment]
@scharlot do you think that the SED above is reasonable ? In particular @OlivierKauffmann was wondering if the flux increase at wl > 20 micron is physical or not... is it emission from warm dust in photoionised regions? does CLOUDY include dust emission in the output continuum that we use to create the ineb files?

**Comment by scharlot** [comment]
@jacopo-chevallard and @OlivierKauffmann, yes this is the emission from dust computed by CLOUDY (self-consistently with the depletion of metals from the gas-phase in our calculations); see Section 2.5 and Figs 14 and 16 (where you can see the characteristic upturn beyond 20µm) of Ferland et al. 2013 (http://adsabs.harvard.edu/abs/2013RMxAA..49..137F)

**Comment by scharlot** [comment]
@jacopo-chevallard and @OlivierKauffmann: (ignore my mention of Fig. 14 in my previous comment, which was something else; Fig. 16 was the one to look at). Here is the typical grain emission spectrum (from the CLOUDY manual)

![image](https://user-images.githubusercontent.com/14793948/49237814-57cc0a80-f3ff-11e8-8ef2-c903d244471b.png)

**Comment by eclake** [comment]
"For the Q spectra, the wavelength and the spectra dimensions mismatch (SED:(7464, 13871), WL:(3184,)), and the access to the Q galaxies characteristics (r1/JADES_Q_mock_r1_v1.2.fits.gz) is still forbidden. Can you do something with this ?"

Sorry to have missed this comment!

Hi @OlivierKauffmann @jacopo-chevallard  - the Q downgraded spectra did get added a little later - I can access them - Jacopo can you please double check that you can download them.  I don't understand why the SF ones would be available but the Q one not!

**Comment by jacopo-chevallard** [comment]
I confirm, the JADES_Q_mock_r1_v1.2.fits.gz is not accessible, it must be because of some permission issue, let me take a look

**Comment by jacopo-chevallard** [comment]
(The discussion of accessing the files is continuing in #10)

**Comment by OlivierKauffmann** [comment]
@eclake - Concerning the Q spectra (both in the r1/ and the r1_30um_cutoff/), there is still the dimension mismatch problem:
- r1_30um_cutoff/JADES_Q_mock_r1_v1.2_spec_5A_30um.fits: SED:(7464, 13871), WL:(3184,)
- r1/JADES_Q_mock_r1_v1.2_spec_5A_30um.fits: SED:(7464, 3035), WL:(3184,)

**Comment by eclake** [comment]
Fixed version only just uploaded, should have said that it wasn't updated on the server yet - now ready to download.

Have I missed anything else on this thread that needs addressing?

**Comment by OlivierKauffmann** [comment]
Thanks, the one in the r1_30um_cutoff/ folder is correct now. 

In a previous comment, I noted that "For the SF spectra, you took a resolution of 25 A above 1.5 microns (total of 15721 points per spectrum), while you previously (v1.1) used 50 A above 1.5 microns and 100 A above 3 microns (total of 3075 points per spectrum). I assume you took a such small resolution to correctly recover the emission lines you mentionned." Can you confirm that ?

**Comment by eclake** [comment]
Before I was using the native resolution of the stellar models without changing anything above ~9300A, which led to the problems of irregular wavelength sampling documented in #4 .  But, yes, it was also to make sure that the lines are taken account of properly.  A possible way of providing smaller files in the future is to provide the lines fluxes separately from the continuum, and using much lower wavelength sampling at longer wavelengths, but that requires a little more setup on my part (I have it written only for the full resolution spectra at the moment).

**Comment by OlivierKauffmann** [comment]
@eclake - I may have found an issue with the SF galaxy catalog/spectra in the r1_30um_cutoff/ folder. There are 302515 objects in the catalog and 302500 in the spectra files. The IDs of the missing objects are 297410, 297411, 302256, 216241, 216242, 216243, 216244, 216245, 216246, 216247, 302257, 302258, 302515, 270140, 270141.

Any idea why these SF galaxies are missing in the spectra files ? They do not seem to have particular characteristics. All of them have stellar mass below 8. I can easily remove them from the catalog but I would be nice to understand why they have been removed from the spectra files

Also, the IDs in the Q galaxy spectra file (between 605031 and 612494) do no match with those in the Q catalog file (between 302516 and 309979). The redshifts correspond tough, so it is just necessary to rename the IDs in the spectra file.

**Comment by OlivierKauffmann** [comment]
Any idea why these SF galaxies are missing in the spectra files ? They do not seem to have particular characteristics. All of them have stellar mass below 8. I can easily remove them from the catalog but I would be nice to understand why they have been removed from the spectra files

**Comment by OlivierKauffmann** [comment]
Also, the IDs in the Q galaxy spectra file (between 605031 and 612494) do no match with those in the Q catalog file (between 302516 and 309979). The redshifts correspond tough, so it is just necessary to rename the IDs in the spectra file.

**Comment by JADES-GTO** [comment]
issue solved in new version, soon to be distributed
